#!/usr/bin/env bash
# echo '
# deb http://deb.debian.org/debian/ bookworm-backports main' | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install git curl nix i3 xorg firefox-esr build-essential
sudo ln -sT /usr/share/doc/nix-bin/examples/nix.sh /etc/profile.d/nix.sh
# fix substitutes
service=/etc/systemd/system/guix-daemon.service
sudo sed -i '/guixbuild/ s/$/ --substitute-urls="https:\/\/bordeaux.guix.gnu.org\ https:\/\/cuirass.genenetwork.org\ http:\/\/ci.guix.trop.in"/' $service

sudo systemctl daemon-reload
sudo systemctl restart guix-daemon

#update root guix
sudo -u root guix pull
sudo systemctl restart guix-daemon

# update guix
guix pull
GUIX_PROFILE="/home/kyurivlis/.config/guix/current"
. "$GUIX_PROFILE/etc/profile"

# nix
sudo adduser kyurivlis nix-users
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
sudo -u kyurivlis nix-channel --update

# consfigure prep
ssh-keygen
ln -sT ~/c/deb/ssh/config ~/.ssh/config
sudo sed -i 's/%sudo	ALL=(ALL:ALL) ALL/%sudo	ALL=(ALL:ALL) NOPASSWD:ALL/' /etc/sudoers

#finally
guix install just guile glibc-locales
GUIX_PROFILE="/home/kyurivlis/.guix-profile"
. "$GUIX_PROFILE/etc/profile"
cd ~/c/deb
just init
cd ~/c/rde
echo /home/kyurivlis/c/rde >> /home/kyurivlis/.config/guix/shell-authorized-directories
guix shell
just bump
just dwim
