# args := if env('FIRST') == 'yep' {`gt -c 'min values at: substituteUrls asOption}
substitutes := if env('FIRST', 'yep') == 'yep' { '--substitute-urls=https://bordeaux.guix.gnu.org\ https://cuirass.genenetwork.org\ http://ci.guix.trop.in\ https://substitutes.nonguix.org' } else { '' }
cfg:= 'cfg.scm'
chans:= 'chans.scm'
profile:= env('GUIX_PROFILE','/run/current-system/profile')

alias hc := homeCfg
alias sc := sysCfg
alias hb := homeBld
alias sb := sysBld
alias g := guix

dwim: homeCfg sysCfg
guix *_='describe':
    {{profile}}/bin/guix {{_}}
cfg *_: (guix _ cfg substitutes)
home *_: (cfg 'home' _)
sys *_:
    sudo --preserve-env=GUIX_PROFILE,FIRST,HOSTNAME TRG='sys' just cfg system {{_}}
homeCfg: (home 'reconfigure')
sysCfg: (sys 'reconfigure')
homeBld: (home 'build')
sysBld: (sys 'build')
pull *_: (guix 'pull -C' chans _ substitutes)
bump: && (pull '-p profile') pull (guix 'describe -f channels >' chans)
    ./bump.scm {{chans}}

repl:
    guile -c '((@ (ares server) run-nrepl-server))'&
       
mkswap $f='/swap/swapfile':
    mkdir /swap
    touch {{f}}
    fallocate -l 512M {{f}}
    mkswap {{f}}
    chmod 0660 {{f}}

nonguix:
	curl https://substitutes.nonguix.org/signing-key.pub > /tmp/nonguix.key
	guix archive --authorize < /tmp/nonguix.key
	rm /tmp/nonguix.key
